USE MASTER 
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME='DLVN')
	DROP DATABASE DLVN
GO
CREATE DATABASE DLVN
ON (NAME='DLVN_DATA' , FILENAME ='F:\DataSet\DLVN_DATABASE\DLVN.MDF')
LOG ON (NAME='DLVN_LOG' , FILENAME ='F:\DataSet\DLVN_DATABASE\DLVN.lDF')
GO
USE DLVN
GO
CREATE TABLE TINH_TP(
	MATP VARCHAR(3) NOT NULL,
	TENTP NVARCHAR(20),
	DT FLOAT ,
	DS BIGINT,
	MIEN NVARCHAR(10)
)
GO
CREATE TABLE BIENGIOI(
	NUOC NVARCHAR(10) NOT NULL,
	MATP VARCHAR(3) NOT NULL
)
GO
CREATE TABLE LANGGIENG(
	MATP VARCHAR(3) NOT NULL ,
	LG  VARCHAR(3) NOT NULL
)
GO
--CREATE KEY
ALTER TABLE TINH_TP
	ADD CONSTRAINT PK_TINHTP PRIMARY KEY(MATP)
ALTER TABLE BIENGIOI
	ADD CONSTRAINT PK_BIENGIOI PRIMARY KEY(NUOC,MATP)
ALTER TABLE LANGGIENG
	ADD CONSTRAINT PK_LANGGIENG PRIMARY KEY(MATP,LG)
ALTER TABLE BIENGIOI
	ADD CONSTRAINT FK_BIENGIOI FOREIGN KEY (MATP) REFERENCES TINH_TP
ALTER TABLE LANGGIENG 
	ADD CONSTRAINT FK_LANGGIENG FOREIGN KEY(MATP) REFERENCES TINH_TP
ALTER TABLE LANGGIENG
	ADD CONSTRAINT FK_LANGGIENG2 FOREIGN KEY(LG) REFERENCES TINH_TP
--INSERT DATABASE 
INSERT INTO TINH_TP(MATP,TENTP,DT,DS,MIEN) VALUES
	('AG',N'AN GIANG',3406,2142709,N'NAM'),
	('BR',N'BÀ RỊA-VŨNG TÀU',1982,996682,N'NAM')
--CÂU 1 : 
-- A) TP CÓ DIỆN TÍCH >=5000KM2
SELECT TENTP,DS 
FROM TINH_TP 
WHERE DT >= 5000
--B) TP CÓ DIỆN TÍCH >=[INPUT] (SINH VIEN NHAP SO BẤT KÌ TỪ BAN PHIM]
DECLARE @DT_INPUT FLOAT
SET @DT_INPUT =10000
SELECT TENTP,DS 
FROM TINH_TP 
WHERE DT >= @DT_INPUT
--CÂU 2 : XUẤT RA TÊN TỈNH,TP CÙNG VOIDWS DIỆN TÍCH CỦA TỈNH,TP
SELECT TENTP,DT 
FROM TINH_TP 
--CÂU 3: THUỘC MIỀN BẮC 
SELECT * 
FROM TINH_TP 
WHERE MIEN = N'Bắc'
--CÂU 4: THUỘC MIỀN [INPUT] (SINH VIÊN NHẬP MỘT MIỀN TỪ BÀN PHÍM)
DECLARE @MIEN_INPUT NVARCHAR(10)
SET @MIEN_INPUT = 'Trung'
SELECT * 
FROM TINH_TP 
WHERE MIEN = @MIEN_INPUT
--CÂU 5 : XUẤT RA CÁC TÊN TỈNH,TP BIÊN GIỚI THUỘC MIỀN [INPUT]
DECLARE @MIEN_INPUT2 NVARCHAR(10)
SET @MIEN_INPUT2 ='Nam'
SELECT DISTINCT TENTP,NUOC 
FROM TINH_TP A ,BIENGIOI B 
WHERE A.MATP=B.MATP AND MIEN = @MIEN_INPUT2
--CÂU 6: DIỆN TÍCH TRUNG BÌNH CỦA CÁC TỈNH , TP (TỔNG DT , TỔNG SỐ TỈNH_TP)
SELECT SUM(DT)/COUNT(MATP) AS DIENTICH_TB 
FROM TINH_TP 
--CÂU 7:DÂN SỐ CÙNG VỚI TÊN TỈNH CỦA CÁC TỈNH,TP CÓ CÙNG DIỆN TÍCH > 7000KM2
SELECT TENTP,DS 
FROM TINH_TP 
WHERE DT > 7000
--CÂU 8 : DÂN SỐ VÀ TÊN TỈNH CÁC TỈNH Ở MIỀN BẮC 
SELECT TENTP,DS 
FROM TINH_TP 
WHERE MIEN =N'Bắc'
--CÂU 9 : MÃ CÁC NƯỚC LÀ BIÊN GIỚI CỦA CÁC TỈNH MIỀN'NAM'
SELECT DISTINCT NUOC 
FROM TINH_TP A ,BIENGIOI B 
WHERE A.MATP=B.MATP AND MIEN= N'Nam'
--CÂU 10:DIỆN TÍCH TRUNG BÌNH CẢU CÁC TỈNH (DÙNG HÀM AVG)
SELECT AVG(DT) AS DIENTICH_TB 
FROM TINH_TP 
--CÂU 11 : MẬT ĐỘ DÂN SỐ CÙNG VỚI TÊN TỈNH , TP CỦA TẤT CẢ CÁC TỈNH THÀNH PHỐ 
SELECT TENTP, ROUND(DS/DT,3) AS MAT_DO 
FROM TINH_TP 
--CÂU 12: TÊN CÁC TỈNH,LÁNG GIỀNG CỦA TỈNH 'LONG AN' 
SELECT TENTP FROM TINH_TP WHERE MATP IN (SELECT LG FROM TINH_TP A ,LANGGIENG B  
										WHERE B.MATP = (SELECT MATP FROM TINH_TP 
														WHERE TENTP =N'LONG AN')) 
--CÂU 13:SỐ LƯỢNG CÁC TỈNH , TP GIÁP VỚI ' CPC'
SELECT COUNT(TENTP) AS SOLUONG 
FROM TINH_TP A ,BIENGIOI B 
WHERE A.MATP = B.MATP AND NUOC ='CPC' 
--CÂU 14: TÊN TỈNH CÓ DIỆN TÍCH LỚN NHẤT
--CÁCH 1 : 
SELECT TOP 1 TENTP
FROM TINH_TP 
ORDER BY DT DESC
--CÂU 15 : TP CÓ MẬT ĐỘ ĐÔNG NHẤT
SELECT TOP 1 TENTP, ROUND(DS/DT,3) AS MAT_DO 
FROM TINH_TP
ORDER BY MAT_DO DESC 
--CÂU 16 : HAI TỈNH,TP GIÁP BIÊN GIỚI HAI NƯỚC KHÁC NHAU
SELECT A.TENTP 
FROM TINH_TP A ,BIENGIOI B
WHERE A.MATP = B.MATP
GROUP BY A.TENTP
HAVING COUNT(NUOC) = 2
--CÂU 17: DANH SÁCH CÁC MIỀM CÙNG VỚI CÁC TỈNH,TP TRONG CÁC MIỀN ĐÓ
SELECT TENTP,MIEN
FROM TINH_TP
ORDER BY MIEN DESC
--CÂU 18: CHO BIẾT TÊN NHỮNG TỈNH,TP CÓ NHIỀU LÁNG GIỀNG NHẤT
SELECT A.TENTP
FROM TINH_TP A , LANGGIENG B
WHERE A.MATP = B.MATP
GROUP BY A.TENTP
HAVING COUNT(LG) = ALL(SELECT TOP 1 COUNT(LG) 
					   FROM LANGGIENG 
					   GROUP BY MATP 
					   ORDER BY COUNT(LG) DESC)
--CÂU 19 : CHO BIẾT NHỮNG TỈNH,TP CÓ DIỆN TÍCH NHỎ HƠN DIỆN TÍCH TRUNG BÌNH CỦA TẤT CẢ TỈNH,TP
SELECT TENTP
FROM TINH_TP
WHERE DT < ALL(SELECT AVG(DT) AS DTTB 
			   FROM TINH_TP )
--CÂU 20: CHO BIẾT TÊN NHỮNG TỈNH,TP GIÁP VỚI CÁC TỈNH,TP Ở MIỀN NAM VÀ KHÔNG PHẢI LÀ MIỀN NAM
SELECT DISTINCT A.TENTP
FROM TINH_TP A , LANGGIENG B 
WHERE A.MATP = B.MATP AND A.MIEN NOT IN (SELECT A.MIEN FROM TINH_TP A , LANGGIENG B WHERE A.MATP = B.LG AND MIEN =N'NAM') 
--CÂU 21 : CHO BIẾT TÊN NHỮNG TỈNH,TP CÓ DIỆN TÍCH LỚN HƠN TẤT CẢ CAC TỈNH , TP LÁNG GIỀNG CỦA NÓ 
SELECT A.TENTP,A.DT,C.TENTP AS LG1 ,C.DT AS D_LG2 
FROM LANGGIENG B 
JOIN TINH_TP A ON A.MATP = B.MATP
JOIN TINH_TP C ON C.MATP = B.LG
WHERE A.DS > C.DT
--CÂU 22 : CHO BIẾT TÊN NHỮNG TỈNH TP MÀ TA CÓ THỂ ĐẾN BẰNG CÁCH ĐI TỪ TPHCM XUYÊN QUA BA TỈNH KHÁC NHAU VÀ CŨNG KHÁC VỚI ĐIỂM XUẤT PHÁT , NHƯNG LÁNG GIỀNG VỚI NHAU