USE MASTER 
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QLBD')
	DROP DATABASE QLBD
GO
CREATE DATABASE QLBD
ON (NAME='QLBD_DATA' , FILENAME ='C:\SQL\QLBD.MDF')
LOG ON (NAME ='QLBD_LOG',FILENAME='C:\SQL\QLBD.LDF')
GO
USE QLBD
CREATE TABLE SAN (
	MASAN CHAR(3) PRIMARY KEY , 
	TENSAN NVARCHAR(50),
	DIACHI NVARCHAR(50)
)
CREATE TABLE DOI (
	MADOI CHAR(20) PRIMARY KEY , 
	TENDOI NVARCHAR(50)
)
GO
CREATE TABLE TRANDAU (
	MATD  CHAR(2) PRIMARY KEY , 
	MASAN CHAR(3) , 
	NGAY DATE ,
	GIO TIME 
	FOREIGN KEY (MASAN) REFERENCES SAN(MASAN)
)
GO
CREATE TABLE CT_TRANDAU(
	MATD CHAR(2) ,
	MADOI CHAR(20),
	SOBANTHANG TINYINT

	PRIMARY KEY (MATD,MADOI) 
)
GO
ALTER TABLE CT_TRANDAU
	ADD CONSTRAINT FK_CT_TRANDAU FOREIGN KEY(MATD) REFERENCES TRANDAU(MATD)
ALTER TABLE CT_TRANDAU 
	ADD CONSTRAINT FK_CT_TRANDAU1 FOREIGN KEY(MADOI) REFERENCES DOI(MADOI)

--CÂU 1 : IN SỐ TRẬN ĐẤU MÀ MỖI ĐỘI THI ĐẤU : HIỆN THỊ : MADOI , TENDOI 
SELECT D.MADOI , D.TENDOI , COUNT(D.MADOI) AS [SỐ TRẬN DẤU ]
FROM DOI D , CT_TRANDAU C 
WHERE D.MADOI = C.MADOI 
GROUP BY D.MADOI , D.TENDOI 
--CÂU 2 : IN KẾT QUẢ TRẬN ĐÂU THEO TỈ SỐ 
SELECT CT1.MATD , CT1.MADOI +' - '+CT2.MADOI AS [TRẬN ĐẤU] ,CT1.SOBANTHANG+ ' - ' + CT2.SOBANTHANG AS [TỈ SỐ]
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2 
WHERE CT1.MATD = CT2.MATD AND CT1.MADOI <> CT2.MADOI
--CÂU 3: IN KẾT QUẢ TRẬN ĐẤU THEO DIỂM 
SELECT CT1.MATD , CT1.MADOI , SUM(CASE WHEN CT1.SOBANTHANG > CT2.SOBANTHANG THEN 3 
									   WHEN CT1.SOBANTHANG = CT2.SOBANTHANG THEN 1
								       ELSE 0 END) AS DIEM 
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2
WHERE CT1.MATD = CT2.MATD AND CT1.MADOI <> CT2.MADOI
GROUP BY CT1.MATD , CT1.MADOI

--CÂU 4 : IN MÃ ĐỘI,TÊN ĐỘI,TỔNG SỐ ĐIỂM 
SELECT CT1.MADOI , TENDOI , SUM(CASE WHEN CT1.SOBANTHANG > CT2.SOBANTHANG THEN 3
									 WHEN CT1.SOBANTHANG = CT2.SOBANTHANG THEN 1
									 ELSE 0 END) AS TONGDIEM
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2 , DOI D
WHERE CT1.MATD = CT2.MATD AND D.MADOI = CT1.MADOI AND CT1.MADOI <> CT2.MADOI
GROUP BY CT1.MADOI , TENDOI 
ORDER BY TONGDIEM DESC
--CÂU 5 : SẮP XẾP DANH SÁCH CÁC ĐỘI ĐỂ BIẾT THỨ HẠNG
SELECT CT1.MADOI , TENDOI , SUM (CASE WHEN CT1.SOBANTHANG > CT2.SOBANTHANG THEN 3 
									  WHEN CT1.SOBANTHANG = CT2.SOBANTHANG THEN 1
									  ELSE 0 END) AS TONGDIEM , (SUM(CT1.SOBANTHANG)-SUM(CT2.SOBANTHANG))AS HIEUSOBANTHANG
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2 , DOI D 
WHERE D.MADOI = CT1.MADOI AND CT1.MATD = CT2.MATD AND CT1.MADOI <> CT2.MADOI
GROUP BY CT1.MADOI , TENDOI 
ORDER BY TONGDIEM  DESC
--CÂU 6 : HIỆN THỊ CÁC TRẬN CHƯA ĐÁ : 
SELECT D1.MADOI , D2.MADOI
FROM DOI D1 , DOI D2 
WHERE D1.MADOI <> D2.MADOI 
EXCEPT 
SELECT CT1.MADOI , CT2.MADOI
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2 
WHERE CT1.MADOI <> CT2.MADOI AND CT1.MATD = CT2.MATD
