USE MASTER 
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QLBD')
	DROP DATABASE QLBD
GO
CREATE DATABASE QLBD
ON (NAME='QLBD_DATA' , FILENAME ='F:\DataSet\QLBD_DATABASE\QLBD.MDF')
LOG ON (NAME ='QLBD_LOG',FILENAME='F:\DataSet\QLBD_DATABASE\QLBD.LDF')
GO
USE QLBD
CREATE TABLE SAN (
	MASAN CHAR(3) PRIMARY KEY , 
	TENSAN NVARCHAR(50),
	DIACHI NVARCHAR(50)
)
CREATE TABLE DOI (
	MADOI CHAR(20) PRIMARY KEY , 
	TENDOI NVARCHAR(50)
)
GO
CREATE TABLE TRANDAU (
	MATD  CHAR(2) PRIMARY KEY , 
	MASAN CHAR(3) , 
	NGAY DATE ,
	GIO TIME 
	FOREIGN KEY (MASAN) REFERENCES SAN(MASAN)
)
GO
CREATE TABLE CT_TRANDAU(
	MATD CHAR(2) ,
	MADOI CHAR(20),
	SOBANTHANG TINYINT

	PRIMARY KEY (MATD,MADOI) 
)
GO
ALTER TABLE CT_TRANDAU
	ADD CONSTRAINT FK_CT_TRANDAU FOREIGN KEY(MATD) REFERENCES TRANDAU(MATD)
ALTER TABLE CT_TRANDAU 
	ADD CONSTRAINT FK_CT_TRANDAU1 FOREIGN KEY(MADOI) REFERENCES DOI(MADOI)

--CÂU 1 : IN SỐ TRẬN ĐẤU MÀ MỖI ĐỘI THI ĐẤU : HIỆN THỊ : MADOI , TENDOI 
SELECT D.MADOI , D.TENDOI , COUNT(D.MADOI) AS [SỐ TRẬN DẤU ]
FROM DOI D , CT_TRANDAU C 
WHERE D.MADOI = C.MADOI 
GROUP BY D.MADOI , D.TENDOI 
--CÂU 2 : IN KẾT QUẢ TRẬN ĐÂU THEO TỈ SỐ 
SELECT CT1.MATD , CT1.MADOI +' - '+CT2.MADOI AS [TRẬN ĐẤU] ,CT1.SOBANTHANG+ ' - ' + CT2.SOBANTHANG AS [TỈ SỐ]
FROM CT_TRANDAU CT1 , CT_TRANDAU CT2 
WHERE CT1.MATD = CT2.MATD AND CT1.MADOI <> CT2.MADOI
--CÂU 3: 
